[directory]
fish_style_pwd_dir_length = 1

[aws]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[git_branch]
symbol = "ğŸŒ± "
ignore_branches = ["main"]

[git_status]
format = '([\[git status $all_status$ahead_behind\]]($style) )'

[nodejs]
symbol = "â¬¢ "
format = 'with [$symbol($version )]($style)'


[python]
symbol = "ğŸ "
format = 'with [${symbol}${pyenv_prefix}(${version})( \(vf $virtualenv\) )]($style) '

[status]
disabled = false

[time]
disabled = false
format = 'ğŸ•™ [$time]($style) '
